Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
#  approot: "http://www.devwork.org/a/"
  approot: "http://ursaminor.informatik.uni-augsburg.de/koeppl"
  copyright: Copyright 2012,2013 Dominik KÃ¶ppl, CC-BY DE 3.0
  #analytics: UA-YOURCODE

Development:
  port: 4000
  approot: "http://ursamajor.informatik.uni-augsburg.de:2235"
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
